server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      defalut-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: car-service
          uri: lb://car-service
          predicates:
            - Path=/car/**
        - id: bike-service
          uri: lb://bike-service
          predicates:
            - Path=/bike/**

  security:
    oauth2:
      client:      
        provider:
          keycloak:
            authorization-uri: http://localhost:8180/auth/realms/microservice-realm/protocol/openid-connect/auth
            userinfo-uri: http://localhost:8180/auth/realms/microservice-realm/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
            token-uri: http://localhost:8180/auth/realms/microservice-realm/protocol/openid-connect/token
        registration:
          microservice-client: 
            provider: keycloak
            client-id: microservice-client
            client-secret: 02d2409d-1d0d-44ab-ba2f-0ca485adcc3e
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/microservice-client"